# Cluster 108

class FunctionMetadataCatalog(BaseModel):
    """
    The `FunctionMetadataCatalog` catalog stores information about the metadata of user-defined functions (Functions).
    Metadata is implemented a key-value pair that can be used to store additional information about the Function.
    It maintains the following information for each attribute:
        `_row_id:` an autogenerated identifier
        `_key: ` key/identifier of the metadata (as a string)
        `_value:` value of the metadata (as a string)
        `_function_id:` the `_row_id` of the `FunctionCatalog` entry to which the attribute belongs
    """
    __tablename__ = 'function_metadata_catalog'
    _key = Column('key', String(100))
    _value = Column('value', TextPickleType())
    _function_id = Column('function_id', Integer, ForeignKey('function_catalog._row_id'))
    __table_args__ = (UniqueConstraint('key', 'function_id'), {})
    _function = relationship('FunctionCatalog', back_populates='_metadata')

    def __init__(self, key: str, value: str, function_id: int):
        self._key = key
        self._value = value
        self._function_id = function_id

    def as_dataclass(self) -> 'FunctionMetadataCatalogEntry':
        return FunctionMetadataCatalogEntry(row_id=self._row_id, key=self._key, value=self._value, function_id=self._function_id, function_name=self._function._name)

