# Cluster 110

class ConfigurationCatalog(BaseModel):
    """The `ConfigurationCatalog` catalog stores all the configuration params.
    `_row_id:` an autogenerated unique identifier.
    `_key:` the key for the config.
    `_value:` the value for the config
    """
    __tablename__ = 'configuration_catalog'
    _key = Column('key', String(100), unique=True)
    _value = Column('value', TextPickleType())

    def __init__(self, key: str, value: any):
        self._key = key
        self._value = value

    def as_dataclass(self) -> 'ConfigurationCatalogEntry':
        return ConfigurationCatalogEntry(row_id=self._row_id, key=self._key, value=self._value)

