# Cluster 111

class FunctionCostCatalog(BaseModel):
    """The `FunctionCostCatalog` catalog stores information about the runtime of user-defined functions (Functions) in the system. It maintains the following information for each Function.
    `_row_id:` an autogenerated unique identifier.
    `_name:` name of the Function
    `_function_id`: the row_id of the Function
    `_cost:` cost of this Function
    """
    __tablename__ = 'function_cost_catalog'
    _function_id = Column('function_id', Integer, ForeignKey('function_catalog._row_id', ondelete='CASCADE'))
    _function_name = Column('name', String(128), ForeignKey('function_catalog.name', ondelete='CASCADE'))
    _cost = Column('cost', Float)

    def __init__(self, function_id: int, name: str, cost: float):
        self._function_id = function_id
        self._function_name = name
        self._cost = cost

    def as_dataclass(self) -> 'FunctionCostCatalogEntry':
        return FunctionCostCatalogEntry(function_id=self._function_id, name=self._function_name, cost=self._cost, row_id=self._row_id)

