# Cluster 16

def make(version: str) -> None:
    """
    Generate README.md.
    :param version: Database version.
    """
    with open('README.md', 'w') as f:
        f.write('nuPlan DB schema. Version {} \n========== \n'.format(version))
        f.write('`This file is automatically generated so do not edit this file. Stay DRY.`\n\n')
        for table in tables:
            jsontabledump(f, tables[table], table)

def jsontabledump(f: TextIO, c: Tuple[str, Dict[str, Tuple[str, str]]], name: str) -> None:
    """
    Dump table schema to the given file.
    :param f: File object to dump the table to.
    :param c: Table schema.
    :param name: Table name.
    """
    f.write('{}\n---------\n'.format(name))
    f.write('\n' + c[0] + '\n')
    f.write('```\n')
    f.write('{}{}\n'.format(name, '{'))
    for key in c[1].keys():
        f.write('   {:27}{} -- {}\n'.format('"' + key + '":', c[1][key][0], c[1][key][1]))
    f.write('{}\n```\n'.format('}'))

