# Cluster 31

class TestAutoGeneratedFiles:
    """Test handling of auto-generated files."""

    def test_pycache_deletion_allowed(self, tmp_path):
        """Test that __pycache__ files can be deleted without reading."""
        from massgen.filesystem_manager._file_operation_tracker import FileOperationTracker
        tracker = FileOperationTracker(enforce_read_before_delete=True)
        pycache_dir = tmp_path / '__pycache__'
        pycache_dir.mkdir()
        pyc_file = pycache_dir / 'test.cpython-313.pyc'
        pyc_file.write_text('fake bytecode')
        can_delete, reason = tracker.can_delete(pyc_file)
        assert can_delete
        assert reason is None

    def test_pyc_file_deletion_allowed(self, tmp_path):
        """Test that .pyc files can be deleted without reading."""
        from massgen.filesystem_manager._file_operation_tracker import FileOperationTracker
        tracker = FileOperationTracker(enforce_read_before_delete=True)
        pyc_file = tmp_path / 'module.pyc'
        pyc_file.write_text('fake bytecode')
        can_delete, reason = tracker.can_delete(pyc_file)
        assert can_delete
        assert reason is None

    def test_pytest_cache_deletion_allowed(self, tmp_path):
        """Test that .pytest_cache can be deleted without reading."""
        from massgen.filesystem_manager._file_operation_tracker import FileOperationTracker
        tracker = FileOperationTracker(enforce_read_before_delete=True)
        cache_dir = tmp_path / '.pytest_cache'
        cache_dir.mkdir()
        cache_file = cache_dir / 'v' / 'cache' / 'nodeids'
        cache_file.parent.mkdir(parents=True)
        cache_file.write_text('test data')
        can_delete, reason = tracker.can_delete(cache_file)
        assert can_delete
        assert reason is None

    def test_regular_file_requires_read(self, tmp_path):
        """Test that regular files still require reading before deletion."""
        from massgen.filesystem_manager._file_operation_tracker import FileOperationTracker
        tracker = FileOperationTracker(enforce_read_before_delete=True)
        py_file = tmp_path / 'module.py'
        py_file.write_text("print('hello')")
        can_delete, reason = tracker.can_delete(py_file)
        assert not can_delete
        assert reason is not None
        assert 'must be read before deletion' in reason

    def test_directory_with_pycache_allowed(self, tmp_path):
        """Test that directories containing only __pycache__ can be deleted."""
        from massgen.filesystem_manager._file_operation_tracker import FileOperationTracker
        tracker = FileOperationTracker(enforce_read_before_delete=True)
        test_dir = tmp_path / 'mymodule'
        test_dir.mkdir()
        pycache_dir = test_dir / '__pycache__'
        pycache_dir.mkdir()
        pyc_file = pycache_dir / 'test.pyc'
        pyc_file.write_text('fake bytecode')
        can_delete, reason = tracker.can_delete_directory(test_dir)
        assert can_delete
        assert reason is None

